### ISSUE TITLE
Time Property Not Preserved When Modifying and Saving a ChaNGa Snapshot

### ISSUE THREAD

**Issue by pedronaethe** [pynbody/pynbody#881]
I am working with a ChaNGa simulation and trying to modify an existing snapshot by adding a new star.  Basically I'm doing:

1. Load the snapshot (e.g., step 150).
2. Add a new star.
3. Save the modified snapshot.

I notice that everything is working great except for the properties of my SimSnap (which only has time).

So to check that I am doing the following:

```
# Printing the properties at this new snapshot
new_snap.properties = old_snap.properties
print(new_snap.properties['time'])

# Writing file
new_snap.write(fmt=pynbody.snapshot.tipsy.TipsySnap, filename=filename, binary_aux_arrays=True)

# Reloading the snapshot
reloaded_snap = pynbody.load(filename)
print("After reloading, properties:", reloaded_snap.properties)
```

And I get as output:
```
1.50e+00 s kpc km**-1
After reloading, properties: {'time': Unit("1.00e+00 s kpc km**-1")}
```

It should be returning 1.5. I'm not sure what I could be doing wrong as I don't have much experience with pynbody. Anyone got a clue on why that happens?

**Comment by apontzen** [comment]
Hmm, weird.

Hard to diagnose this as it stands. Ideally please provide a fully reproducible example, i.e. with everything we need to run and see the problem for ourselves. 

Failing that, could you provide a bit more detail, e.g. is this cosmological or non-cosmological? What does the changa parameter file look like, and is it definitely being found correctly (i.e. in the right folder)?  Are any warnings emitted when you load or save?

**Comment by pedronaethe** [comment]
Hey! yes, very weird. I managed to create an example

Basically, I'm copying this file and saving it and then reloading

```
import pynbody
import numpy as np

[test.tar.gz](https://github.com/user-attachments/files/18892384/test.tar.gz)

# Load the original snapshot
sss = "./onlytesting/dwarfR4.1xmassFB20BH.000001"
f = pynbody.load(sss)
f.physical_units()
# Assign particle IDs to stars
f.properties['time'] = f.properties['time'] * 5
f.s["pid"] = np.arange(len(f.s))

# Save the modified snapshot
filename = "./onlytesting/test"
f.write(fmt=pynbody.snapshot.tipsy.TipsySnap, filename=filename, binary_aux_arrays=True)

# Reload the snapshot
reloaded_snap = pynbody.load(filename)

# Compare time properties
print("Original time property:", f.properties.get("time"))
print("Reloaded time property:", reloaded_snap.properties.get("time"))
```

the output I'm getting is
```
Original time property: 1.29e-01 kpc s km**-1
Reloaded time property: 1.00e+00 s kpc km**-1
/path/pynbody/simdict.py:107: RuntimeWarning: Assuming default value for property 'a'=1.00e+00
  warnings.warn("Assuming default value for property '{}'={:.2e}".format(
```

I'm attaching the tar.gz file of the folder containing the param and the file. Let me know if you can run it



[test.tar.gz](https://github.com/user-attachments/files/18892369/test.tar.gz)

**Comment by apontzen** [comment]
It turns out the issue here is that pynbody assumed by default your output will be cosmological. I am not really sure why.

I fixed this in #882 . Or, if you want to use the existing version of pynbody you can also pass `cosmological=False` directly to `write(...)`. 

Let me know how it goes

**Comment by pedronaethe** [comment]
It worked out for the example, however, I'm still getting some inconsistencies for the full code. When running:
(s is the SimSnap of the old file and new_snap is the one being created)
 ```
print("Properties: new: ",new_snap.properties['time'].in_units(new_snap.s['tform'].units), "Old:", s.properties['time'].in_units(s.s['tform'].units))

new_snap.write(fmt=pynbody.snapshot.tipsy.TipsySnap, filename=filename, binary_aux_arrays=True, cosmological = False)

# Reload the snapshot
reloaded_snap = pynbody.load(filename)
print("After reloading, properties:", reloaded_snap.properties['time'].in_units(reloaded_snap.s['tform'].units))
```

I get slightly different results:

```
Properties: new:  1.499999999999704 Old: 1.499999999999704
After reloading, properties: 1.5014413837280831
```

I checked that by doing s.physical_units() I get the same value of the "after reloading" print statement. Why do I get the value of the reloaded_snap in physical units when loading it already? I also realized that when doing reloaded_snap.physical_units() I get a different value:
`After reloading using sim_snap.physical_units(), properties: 1.5028841525144971`

It appears that some properties, such as `tform`, are only correct after executing `physical_units()`, even though the time property seems to be in physical units before that. This may be related to the script, but is it something obvious that I am missing?

**Comment by apontzen** [comment]
Unfortunately the tipsy format is just not very explicit when it comes to units, so pynbody has to guess the user's intent. The guesses might not be optimal for your use case. I'd recommend calling `new_snap.original_units()` before writing, or just never call `physical_units()` on something you are going to write to disk, for maximum consistency. If the problems persist after that, please open a new issue as it's a separate thing - I'm going to close this one as resolved.
